credentials:
  usernames:
    admin:
      name: admin
      password: admin
    bmwuser:
      name: bmwuser
      password: bmwuser
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name