# This docker file can be used to build the api local 

# Start from the official Python base image.
FROM python:3.10

# This is where we'll put the requirements.txt file and the app directory.
WORKDIR /code

# Copy the file with the requirements to the /code directory.
COPY ./requirements.txt /code/requirements.txt
COPY ./__init__.py /code/__init__.py
COPY ./setup.py /code/setup.py
COPY ./final_models /code/final_models
COPY ./data/processed /code/data/processed
COPY ./src/__init__.py /code/src/__init__.py
COPY ./src/config.py /code/src/config.py
COPY ./src/data_pipeline /code/src/data_pipeline
COPY ./src/deployment_pipeline /code/src/deployment_pipeline

# Install the package dependencies in the requirements file.
RUN apt-get update && apt-get install -y git
RUN pip install -i https://nexus.bmwgroup.net/repository/pypi/simple -r /code/requirements.txt
RUN python /code/setup.py install

ENV PYTHONPATH "${PYTHONPATH}:/code/src"

# Start API
CMD ["uvicorn", "src.deployment_pipeline.api:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "7070"]
