version: '3.8'
services:
  api:
    build: 
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "7070:7070"
    restart: on-failure
    
  website:
    build: 
      context: ./
      dockerfile: ./docker/website/Dockerfile
    ports:
     - "7071:7071"
    restart: on-failure
    depends_on:
      - api
