folder_processed_dataset: data/processed/20231119_0341/ 
experiment_path: src/deep_learning_pipeline/trained_models

earlystopping_metric: valid_loss            # default = valid_loss 
early_stopping_min_delta: 0.00001           # default = 0.0001
early_stopping_mode: min                    # default = min   -   For valid_loss, lower is better
early_stopping_patience: 10                 # default = 30    -   No. of epochs of degradation training will wait before terminating
max_epochs: 200                             # default = 200

task: classification                        # default = classification
loss: CrossEntropyLoss                      # default = CrossEntropyLoss
hyperparameter:
  layers:
    - 16-8-4
    - 256-128-64
    - 1024-512-256
  activation_functions:
    - LeakyReLU
    - ReLU
    - Sigmoid
  batch_size: 
    - 8
    - 128
    - 512
  dropout: 
    - 0
    - 0.1
    - 0.3
target:                                                 # target should always be a list. Multi-targets are only supported for regression. Multi-Task Classification is not implemented
  - Relevant fuer Messung                               # classes: Ja and Nein
target_classes:
  - Ja                                                # Class will be mapped to 1
  - Nein                                                  # Class will be mapped to 0
continuous_cols: 
  - volume
  - Wert
  - center_x
  - center_y
  - center_z
  - length
  - width
  - height
  - theta_x
  - theta_y
  - theta_z
text_cols:
  - Benennung (bereinigt)
#continuous_feature_transform: quantile_normal
normalize_continuous_features: False

k-folds: 4
top_x_models_for_cv: 0.05