paths:
 folder_processed_dataset: data/processed/31072023_1319/

general_params:
 seed: 42
 cut_percent_of_front: 0.18
 relevant_features:
   - Sachnummer
   - Benennung (dt)
   - X-Min
   - X-Max
   - Y-Min
   - Y-Max
   - Z-Min
   - Z-Max
   - ox
   - oy
   - oz
   - xx
   - xy
   - xz
   - yx
   - yy
   - yz
   - zx
   - zy
   - zz
   - Wert
   - Einheit
   - Gewichtsart
   - L-Kz.
   - Kurzname
   - L/R-Kz.
   - Modul (Nr)
   - Code
 check_features_for_nan_values:
   - Sachnummer
   - Benennung (dt)
   - X-Min
   - X-Max
   - Y-Min
   - Y-Max
   - Z-Min
   - Z-Max
   - ox
   - oy
   - oz
   - xx
   - xy
   - xz
   - yx
   - yy
   - yz
   - zx
   - zy
   - zz
 features_for_model:
   - volume
   - Wert
   - center_x
   - center_y
   - center_z
   - length
   - width
   - height
   - theta_x
   - theta_y
   - theta_z
 bounding_box_features_original:
   - X-Min
   - X-Max
   - Y-Min
   - Y-Max
   - Z-Min
   - Z-Max
   - ox
   - oy
   - oz
   - xx
   - xy
   - xz
   - yx
   - yy
   - yz
   - zx
   - zy
   - zz
   - Wert
 keep_modules:
   - FBEP
   - CE05
   - CD07
 car_part_designation: Benennung (dt)
 use_only_text: false

prediction_settings:
  prediction_threshold: 0.65

train_settings:
 k-folds: 4
 ml-method: catboost
 early_stopping: 50
 train_val_split: 0.3
 val_test_split: 0.5
 top_x_models_for_cv: 0.10
 n_estimators: 10000

gpt_settings:
 temperature: 0.6
 max_tokens: 200
 top_p: 1
 n: 1

lgbm_params_binary:
 boosting_type: gbdt
 metrics:
   - auc
   - binary_logloss

lgbm_params_multiclass:
 boosting_type: gbdt
 metrics:
   - auc_mu
   - multi_logloss

lgbm_hyperparameter:
 lr:
   - 0.05
   - 0.07
   - 0.1
 max_depth:
   - 3
   - 5
   - 7
 colsample_bytree:
   - 0.5
   - 0.7
   - 0.9
 min_child_samples:
   - 20
   - 30
   - 40

xgb_params_binary:
 boosting_type: gbtree
 metrics:
   - auc
   - logloss

xgb_params_multiclass:
 boosting_type: gbtree
 metrics:
   - auc
   - mlogloss

xgb_hyperparameter:
 lr:
   - 0.05
   - 0.1
   - 0.3
 max_depth:
   - 4
   - 6
   - 9
 colsample_bytree:
   - 0.5
   - 0.7
   - 0.9
 gamma:
   - 0
   - 0.2
   - 0.5

cb_params_binary:
 boosting_type: Plain
 metrics:
   - AUC
   - Logloss

cb_params_multiclass:
 boosting_type: Plain
 metrics:
   - AUC
   - MultiClass

cb_hyperparameter:
 lr:
   - 0.05
   - 0.07
   - 0.1
 depth:
   - 4
   - 6
   - 9
 colsample_bylevel:
   - 0.5
   - 0.7
   - 0.9
 min_data_in_leaf:
   - 20
   - 30
   - 40

convert_dict:
 X-Min: float
 X-Max: float
 Y-Min: float
 Y-Max: float
 Z-Min: float
 Z-Max: float
 Wert: float
 ox: float
 oy: float
 oz: float
 xx: float
 xy: float
 xz: float
 yx: float
 yy: float
 yz: float
 zx: float
 zy: float
 zz: float